version: "3.3"
services: 
  py1:
    build: ./flask_app
    ports:
      - "5001:5000"
  py2:
    build: ./flask_app_2
    ports:
      - "5002:5000"
  py3:
    build: ./flask_app_3
    ports:
      - "5003:5000"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6000:6000"
    volumes:
      - db:/var/lib/postregsql/data
  
volumes:
  db:
    driver: local